# fly.toml app configuration file generated for tokyo-landprice-rag on 2026-01-11T00:10:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tokyo-landprice-rag'
primary_region = 'nrt'

[build]
  image = "qdrant/qdrant:v1.16.3"

[env]
  QDRANT__SERVICE__HTTP_PORT = "6333"
  QDRANT__STORAGE__PATH = "/qdrant/storage"

[[services]]
  internal_port = 6333
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[mounts]]
  source = "qdrant_data"
  destination = "/qdrant/storage"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
