services:
  client:
    image: tokyo-landprice-rag/client:latest
    container_name: tokyo-landprice-rag-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/app/
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - storage

  storage:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: tokyo-landprice-rag-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    env_file:
      - .env
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    container_name: tokyo-landprice-rag-mc
    depends_on:
      - storage
    restart: "on-failure"
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set minio http://tokyo-landprice-rag-storage:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb minio/${MINIO_BUCKET_NAME} || true;
      mc anonymous set public minio/${MINIO_BUCKET_NAME};
      exit 0;
      "

volumes:
  storage_data:
    driver: local
