on:
  push:
    branches:
      - main
    paths:
      - "qdrant/fly.toml"

jobs:
  deploy-qdrant:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./qdrant

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Validate Fly.io configuration
        run: flyctl config validate
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
